# Hexo 配置文件
## 文档: https://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 网站基本信息配置
title: Solar Bolg
subtitle: 接受不完美
author: Leo
description: 'Solar的博客'
language: zh-CN
keywords:
timezone:

# 网址配置
## 在这里设置你的网站 URL，例如使用 GitHub Pages 时，设置为 'https://username.github.io/project'
url: https://blog.maxcosmos.top
root: /
#permalink: :year/:month/:day/:title/
#permalink: :abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # 设置为 false 可以去除 URL 中的 'index.html'
  trailing_html: true # 设置为 false 可以去除 URL 中的 '.html'
abbrlink:
  alg: crc32 #算法： crc16(默认) 和 crc32
  rep: hex #进制： dec(默认) 和 hex

# 目录配置
source_dir: source          # 源文件目录
public_dir: .temp          # 生成的静态文件目录
tag_dir: tags              # 标签目录
archive_dir: archives      # 归档目录
category_dir: categories   # 分类目录
code_dir: downloads/code   # 代码目录
i18n_dir: :lang           # 国际化目录
skip_render: README.md     # 跳过渲染的文件

# 写作配置
new_post_name: :title.md   # 新文章的文件名格式
default_layout: post       # 默认布局
titlecase: false          # 标题转换为大写
external_link:
  enable: true            # 在新标签页中打开外部链接
  field: site            # 应用于整个网站
  exclude: ''            # 排除的链接
filename_case: 0          # 文件名转换为小写
render_drafts: false      # 是否渲染草稿
post_asset_folder: false  # 是否启用资源文件夹
relative_link: false      # 是否使用相对链接
future: true             # 是否显示未来的文章

# 代码高亮配置
highlight:
  enable: true           # 是否启用代码高亮
  line_number: true      # 显示行号
  auto_detect: true      # 自动检测语言
  tab_replace: ''        # 替换 tab 的字符
  wrap: true            # 是否自动换行
  hljs: false           # 是否使用 highlight.js
prismjs:
  enable: false         # 是否启用 prism.js
  preprocess: true      # 是否预处理
  line_number: true     # 显示行号
  tab_replace: ''       # 替换 tab 的字符

# 隐藏文章配置
hide_posts:
  filter: hidden        # 隐藏文章的标记
  public_generators: [] # 指定隐藏文章可见的位置
  noindex: true        # 为隐藏文章添加 noindex 标签

# 首页设置
index_generator:
  path: ''             # 首页路径
  per_page: 10         # 每页显示的文章数量
  order_by: -date      # 文章排序方式

# 分类和标签
default_category: uncategorized  # 默认分类
category_map:                    # 分类别名
tag_map:                        # 标签别名

# 元数据元素
meta_generator: true            # 是否生成 meta 标签

# 日期 / 时间格式
date_format: YYYY-MM-DD         # 日期格式
time_format: HH:mm:ss          # 时间格式
updated_option: 'mtime'        # 更新时间选项

# 分页配置
per_page: 10                   # 每页显示的文章数量
pagination_dir: page           # 分页目录

# 包含/排除文件
include:                       # 包含的文件
exclude:                       # 排除的文件
ignore:                       # 忽略的文件

# 扩展插件
Plugins: hexo-generator-cname  # 启用的插件

# 主题配置
theme: next                    # 使用的主题

# 搜索配置
search:
  path: search.xml            # 搜索文件路径
  field: post                # 搜索范围
  format: html               # 搜索格式
  limit: 10000              # 搜索限制

# 字数统计和阅读时间
symbols_count_time:
  symbols: true              # 显示字数统计
  total_symbols: true        # 显示总字数
  time: true                # 显示阅读时间
  total_time: true          # 显示总阅读时间

# index2 生成器配置
index2_include_index: true    # 是否包含默认的索引生成器

index2_generator:
  per_page: 10               # 每页文章数
  order_by: -date            # 排序方式
  exclude:
    - tag hide               # 排除带有 hide 标签的文章
    - category hide          # 排除带有 hide 分类的文章

# 部署配置
deploy:
  type: git                  # 部署类型
  repo: git@github.com:dunwu/blog.git  # 仓库地址
  branch: gh-pages           # 部署分支
  message: Update blog.      # 提交信息
